accessLog: {}
api: {}

certificatesResolvers:
  letsencrypt:
    acme:
      email: gandro@gmx.net
      storage: /etc/traefik/acme/letsencrypt.json
      tlsChallenge: {}

entryPoints:
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt

log:
  level: INFO

providers:
  docker:
    exposedByDefault: false
    defaultRule: "Host(`{{ normalize .Name }}.gandro.dev`)"
    endpoint: "unix:///var/run/docker.sock"
  file:
    directory: /etc/traefik/conf.d