version: "3"
services:
  wireguard:
    build:
      context: ./wireguard
    privileged: true
    volumes:
      - ./config:/etc/wireguard/:z,ro
    ports:
      - 51820:51820/udp
    restart: always
